services:
  - type: web
    name: terminax-frontend
    env: static
    rootDir: ./client
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        headers:
          Cache-Control: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
